run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 4m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - integration
    - contract_test_provider
    - contract_test_consumer

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: line-number

  # print lines of code with issue, default is true
  print-issued-lines: false

linters:
  # Start with all linters disabled and white list wanted linters
  disable-all: true

  # Enabled linters
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # Linters that are not used
  # disable:
  #   - lll
  #   - gochecknoglobals
  #   - goconst
  #   - maligned
  #   - godox
  #   - funlen
  #   - wsl
  #   - gomnd

  # Run only linter supporting fast option
  fast: false

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:
    - ".*DNs.*should be.*DNS.*"

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: svc/
      text: "should have comment"
      linters:
        - golint

    - path: svc/
      text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
